package game.items;

public enum Rotation {
    VERTICAL,
    HORIZONTAL,
    VERTICAL_HORIZONTAL_LEFT,
    VERTICAL_HORIZONTAL_RIGHT,
    HORIZONTAL_VERTICAL_LEFT,
    HORIZONTAL_VERTICAL_RIGHT,
    CROSS
}
